import React, { useEffect, useState } from 'react';
import { 
  Grid, Paper, Typography, Chip, Box, Container, IconButton, TextField, Button 
} from '@mui/material';
import PrintIcon from '@mui/icons-material/Print';
import SearchIcon from '@mui/icons-material/Search';
import AddCircleIcon from '@mui/icons-material/AddCircle';
import SummarizeIcon from '@mui/icons-material/Summarize';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // Ensure you installed this: npm install jspdf-autotable
import api from '../api/axiosConfig';
import StatCharts from '../components/StatCharts';
import { useNavigate } from 'react-router-dom';

export default function BranchDashboard() {
  const [tickets, setTickets] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [dateRange, setDateRange] = useState({ start: '', end: '' });

  const user = JSON.parse(localStorage.getItem('user'));
  const navigate = useNavigate();

  // 1. Load Tickets (Filtered by Branch)
  useEffect(() => {
    const fetchTickets = async () => {
      try {
        const res = await api.get('/tickets/all');
        // SECURITY: Only show tickets belonging to THIS branch
        const myTickets = res.data.filter(t => t.branchName === user.branchName);
        setTickets(myTickets);
      } catch (error) {
        console.error("Error loading tickets", error);
      }
    };
    fetchTickets();
  }, [user.branchName]);

  // 2. Advanced Filtering Logic (Search + Calendar)
  const getFilteredTickets = () => {
    return tickets.filter(ticket => {
      // Search Filter
      if (searchTerm && !ticket.errorType.toLowerCase().includes(searchTerm.toLowerCase()) && !ticket.id.includes(searchTerm)) {
        return false;
      }
      // Date Range Filter
      if (dateRange.start && ticket.createdDate < dateRange.start) return false;
      if (dateRange.end) {
          const ticketDate = ticket.createdDate.split('T')[0];
          if (ticketDate > dateRange.end) return false;
      }
      return true;
    });
  };

  const displayedTickets = getFilteredTickets();

  // 3. Generate Report (PDF Table)
  const generateReport = () => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(0, 86, 179);
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(`${user.branchName} Branch Report`, 14, 13);
    
    // Sub-header
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated By: ${user.username}`, 14, 28);
    doc.text(`Date: ${new Date().toLocaleString()}`, 150, 28);

    // Table Data
    const tableColumn = ["ID", "Category", "Issue", "Date", "Status"];
    const tableRows = [];

    displayedTickets.forEach(ticket => {
      const dateStr = new Date(ticket.createdDate).toLocaleDateString();
      const ticketData = [
        ticket.id,
        ticket.errorCategory,
        ticket.errorType,
        dateStr,
        ticket.status
      ];
      tableRows.push(ticketData);
    });

    // Generate Table
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 35,
      theme: 'grid',
      headStyles: { fillColor: [0, 86, 179] }
    });

    doc.save(`${user.branchName}_Report.pdf`);
  };

  // 4. Single Job Card Print
  const downloadJobCard = (ticket) => {
    const doc = new jsPDF();
    doc.text(`NTMI Job Card (Copy)`, 10, 10);
    doc.text(`Ticket ID: ${ticket.id}`, 10, 20);
    doc.text(`Issue: ${ticket.description}`, 10, 30);
    doc.text(`Status: ${ticket.status}`, 10, 40);
    doc.save(`MyTicket_${ticket.id}.pdf`);
  };

  return (
    <Container maxWidth="lg">
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
        <Typography variant="h4" color="primary">
            {user.branchName} Dashboard
        </Typography>
        <Button 
            variant="contained" 
            startIcon={<AddCircleIcon />} 
            onClick={() => navigate('/create')}
        >
            Raise New Ticket
        </Button>
      </Box>

      {/* DYNAMIC CHART (Updates with filters) */}
      <StatCharts tickets={displayedTickets} />

      {/* TOOLBAR: Search, Date Filter, Report Button */}
      <Paper sx={{ p: 2, mb: 3, display: 'flex', flexDirection: 'column', gap: 2 }}>
        
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 2 }}>
             {/* Search */}
             <Box sx={{ display: 'flex', alignItems: 'center', flexGrow: 1 }}>
                <SearchIcon color="action" sx={{ mr: 1 }} />
                <TextField 
                    fullWidth 
                    variant="standard" 
                    placeholder="Search my tickets..." 
                    InputProps={{ disableUnderline: true }}
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                />
             </Box>

             {/* Report Button */}
             <Button 
                variant="outlined" 
                color="secondary" 
                startIcon={<SummarizeIcon />} 
                onClick={generateReport}
             >
                Download Report
             </Button>
        </Box>

        {/* Date Filter Inputs */}
        <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', bgcolor: '#f5f5f5', p: 1, borderRadius: 1 }}>
            <Typography variant="body2">Filter by Date:</Typography>
            <TextField 
                type="date" 
                size="small" 
                label="Start"
                InputLabelProps={{ shrink: true }} 
                value={dateRange.start} 
                onChange={(e) => setDateRange({...dateRange, start: e.target.value})} 
            />
            <TextField 
                type="date" 
                size="small" 
                label="End"
                InputLabelProps={{ shrink: true }} 
                value={dateRange.end} 
                onChange={(e) => setDateRange({...dateRange, end: e.target.value})} 
            />
            <Button size="small" onClick={() => setDateRange({ start: '', end: '' })}>Clear</Button>
        </Box>
      </Paper>

      {/* TICKET GRID */}
      <Grid container spacing={3}>
        {displayedTickets.length > 0 ? (
            displayedTickets.map((ticket) => (
            <Grid item xs={12} md={6} lg={4} key={ticket.id}>
                <Paper sx={{ 
                    p: 2, 
                    borderLeft: `6px solid ${ticket.status === 'PENDING' ? '#d32f2f' : ticket.status === 'IN_PROGRESS' ? '#ed6c02' : '#2e7d32'}`,
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between'
                }}>
                
                <div>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                        <Typography variant="h6" color="primary">#{ticket.id}</Typography>
                        <IconButton onClick={() => downloadJobCard(ticket)}><PrintIcon /></IconButton>
                    </Box>
                    
                    <Typography variant="caption" display="block" color="textSecondary" gutterBottom>
                        {new Date(ticket.createdDate).toLocaleString()}
                    </Typography>

                    <Typography fontWeight="bold" sx={{ mt: 1 }}>{ticket.errorCategory} &gt; {ticket.errorType}</Typography>
                    <Typography variant="body2" sx={{ my: 1, color: '#555' }}>"{ticket.description}"</Typography>
                </div>

                <Box sx={{ mt: 2, pt: 2, borderTop: '1px solid #eee', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Chip 
                        label={ticket.status.replace('_', ' ')} 
                        color={ticket.status === 'PENDING' ? 'error' : ticket.status === 'IN_PROGRESS' ? 'warning' : 'success'} 
                        size="small"
                    />
                    
                    {ticket.fixedBy ? (
                        <Typography variant="caption" sx={{ color: 'blue', fontWeight: 'bold' }}>
                           Handling: {ticket.fixedBy}
                        </Typography>
                    ) : (
                        <Typography variant="caption" sx={{ color: '#999', fontStyle: 'italic' }}>
                           Waiting for Ops...
                        </Typography>
                    )}
                </Box>
                </Paper>
            </Grid>
            ))
        ) : (
            <Box sx={{ width: '100%', textAlign: 'center', mt: 4, color: '#888' }}>
                <Typography variant="h6">No tickets found.</Typography>
                <Typography variant="body2">Adjust your filters to see more.</Typography>
            </Box>
        )}
      </Grid>
    </Container>
  );
}