import React, { useEffect, useState } from 'react';
import { 
  Grid, Paper, Typography, Button, Chip, Box, Container, IconButton, TextField, ToggleButton, ToggleButtonGroup 
} from '@mui/material';
import PrintIcon from '@mui/icons-material/Print';
import SearchIcon from '@mui/icons-material/Search';
import SummarizeIcon from '@mui/icons-material/Summarize';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // <--- FIXED IMPORT
import api from '../api/axiosConfig';
import StatCharts from '../components/StatCharts';

export default function Dashboard() {
  const [tickets, setTickets] = useState([]);
  const [viewMode, setViewMode] = useState('today'); 
  const [searchTerm, setSearchTerm] = useState('');
  const [dateRange, setDateRange] = useState({ start: '', end: '' });
  
  const currentUser = JSON.parse(localStorage.getItem('user'));

  const loadTickets = async () => {
    try {
      const response = await api.get('/tickets/all');
      setTickets(response.data);
    } catch (error) {
      console.error("Error loading tickets:", error);
    }
  };

  useEffect(() => { loadTickets(); }, []);

  const updateStatus = async (id, status) => {
    try {
      await api.put(`/tickets/update/${id}`, {
        status: status,
        username: currentUser.username 
      });
      loadTickets(); 
    } catch (error) {
      alert(error.response?.data?.message || "Error updating ticket.");
    }
  };

  const getFilteredTickets = () => {
    const todayStr = new Date().toISOString().split('T')[0]; 
    return tickets.filter(ticket => {
      if (searchTerm && !ticket.branchName.toLowerCase().includes(searchTerm.toLowerCase()) && !ticket.id.includes(searchTerm)) return false;
      if (dateRange.start && ticket.createdDate < dateRange.start) return false;
      if (dateRange.end) {
          const ticketDate = ticket.createdDate.split('T')[0];
          if (ticketDate > dateRange.end) return false;
      }
      if (viewMode === 'today') {
        const createdDate = ticket.createdDate ? ticket.createdDate.split('T')[0] : '';
        return ticket.status === 'PENDING' || ticket.status === 'IN_PROGRESS' || createdDate === todayStr;
      } 
      return true;
    });
  };

  const displayedTickets = getFilteredTickets();

  // --- REPORT GENERATOR ---
  const generateReport = () => {
    const doc = new jsPDF();

    doc.setFillColor(0, 86, 179);
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text("NTMI Operations Report", 14, 13);
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated By: ${currentUser.username}`, 14, 28);
    doc.text(`Date: ${new Date().toLocaleString()}`, 150, 28);

    const tableColumn = ["ID", "Branch", "Category", "Fixed By", "Date", "Status"];
    const tableRows = [];

    displayedTickets.forEach(ticket => {
      const dateStr = new Date(ticket.createdDate).toLocaleDateString();
      const ticketData = [
        ticket.id,
        ticket.branchName,
        ticket.errorCategory,
        ticket.fixedBy || "Pending",
        dateStr,
        ticket.status
      ];
      tableRows.push(ticketData);
    });

    // FIXED: Using autoTable(doc, ...) syntax
    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 35,
      theme: 'grid',
      headStyles: { fillColor: [0, 86, 179] }
    });

    doc.save("NTMI_Report.pdf");
  };

  // --- SINGLE JOB CARD ---
  const downloadJobCard = (ticket) => {
    const doc = new jsPDF();
    doc.text(`Job Card: ${ticket.id}`, 10, 10);
    doc.text(`Issue: ${ticket.description}`, 10, 20);
    doc.save(`Job_${ticket.id}.pdf`);
  };

  return (
    <Container maxWidth="lg">
      <Typography variant="h4" gutterBottom sx={{ mb: 4, color: '#0056b3' }}>Operations Dashboard</Typography>
      <StatCharts tickets={displayedTickets} />

      <Paper sx={{ p: 2, mb: 3, display: 'flex', flexDirection: 'column', gap: 2 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 2 }}>
            <ToggleButtonGroup color="primary" value={viewMode} exclusive onChange={(e, newView) => { if(newView) setViewMode(newView); }}>
              <ToggleButton value="today">Today's Jobs</ToggleButton>
              <ToggleButton value="history">Full History</ToggleButton>
            </ToggleButtonGroup>
            <Box sx={{ display: 'flex', gap: 1 }}>
                 <TextField size="small" placeholder="Search..." InputProps={{ startAdornment: <SearchIcon color="action" sx={{ mr: 1 }} /> }} value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} />
                 <Button variant="contained" color="secondary" startIcon={<SummarizeIcon />} onClick={generateReport}>Report</Button>
            </Box>
        </Box>
        {viewMode === 'history' && (
            <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', bgcolor: '#f5f5f5', p: 1, borderRadius: 1 }}>
                <Typography variant="body2">Filter Date:</Typography>
                <TextField type="date" size="small" value={dateRange.start} onChange={(e) => setDateRange({...dateRange, start: e.target.value})} />
                <TextField type="date" size="small" value={dateRange.end} onChange={(e) => setDateRange({...dateRange, end: e.target.value})} />
                <Button onClick={() => setDateRange({ start: '', end: '' })}>Clear</Button>
            </Box>
        )}
      </Paper>

      <Grid container spacing={3}>
        {displayedTickets.map((ticket) => (
          <Grid item xs={12} md={6} lg={4} key={ticket.id}>
             <Paper sx={{ p: 2, borderLeft: `6px solid ${ticket.status === 'PENDING' ? '#d32f2f' : ticket.status === 'IN_PROGRESS' ? '#ed6c02' : '#2e7d32'}` }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between' }}>
                  <Typography variant="h6">{ticket.branchName}</Typography>
                  <IconButton onClick={() => downloadJobCard(ticket)}><PrintIcon /></IconButton>
              </Box>
              <Typography variant="caption">{new Date(ticket.createdDate).toLocaleString()}</Typography>
              <Typography fontWeight="bold">{ticket.errorCategory}</Typography>
              <Typography variant="body2" sx={{ my: 1 }}>"{ticket.description}"</Typography>
              {ticket.fixedBy && <Typography variant="caption" sx={{ display: 'block', mt: 1, color: 'blue' }}>🔧 Fixed By: {ticket.fixedBy}</Typography>}
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Chip label={ticket.status} color={ticket.status === 'PENDING' ? 'error' : ticket.status === 'IN_PROGRESS' ? 'warning' : 'success'} />
                {ticket.status === 'PENDING' && <Button variant="contained" color="warning" size="small" onClick={() => updateStatus(ticket.id, 'IN_PROGRESS')}>Start</Button>}
                {ticket.status === 'IN_PROGRESS' && <Button variant="contained" color="success" size="small" disabled={ticket.fixedBy && ticket.fixedBy !== currentUser.username} onClick={() => updateStatus(ticket.id, 'COMPLETED')}>Complete</Button>}
              </Box>
            </Paper>
          </Grid>
        ))}
      </Grid>
    </Container>
  );
}